"""ondelete

Revision ID: f366b824f054
Revises: 3c0a474d46c7
Create Date: 2024-07-02 22:12:48.675954

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f366b824f054'
down_revision: Union[str, None] = '3c0a474d46c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('history_user_id_fkey', 'history', type_='foreignkey')
    op.create_foreign_key(None, 'history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_role_associations_user_id_fkey', 'user_role_associations', type_='foreignkey')
    op.drop_constraint('user_role_associations_role_id_fkey', 'user_role_associations', type_='foreignkey')
    op.create_foreign_key(None, 'user_role_associations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_role_associations', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role_associations', type_='foreignkey')
    op.drop_constraint(None, 'user_role_associations', type_='foreignkey')
    op.create_foreign_key('user_role_associations_role_id_fkey', 'user_role_associations', 'roles', ['role_id'], ['id'])
    op.create_foreign_key('user_role_associations_user_id_fkey', 'user_role_associations', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.create_foreign_key('history_user_id_fkey', 'history', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
