# Generated by Django 4.2.11 on 2024-08-09 07:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [

        migrations.RunSQL(
            sql="""
    CREATE SCHEMA IF NOT EXISTS content;
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    """,
            reverse_sql="""
    DROP SCHEMA content;
    DROP EXTENSION "uuid-ossp";
    """
        ),

        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("verified", models.BooleanField(default=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": 'content"."user',
            },
        ),
    ]
